---
all:
  children:
    dev:
      hosts:
        localhost:
  vars:
    env: dev
    aap_hostname: "<AAP_DEV_GATEWAY_URL>"
    aap_username: "{{ aap_user }}"
    aap_password: "{{ aap_pass }}"
    aap_validate_certs: <AAP_DEV_VALIDATE_CERTS>
...
