---
all:
  children:
    staging:
      hosts:
        localhost:
  vars:
    env: staging
    aap_hostname: "<AAP_STAGING_GATEWAY_URL>"
    aap_username: "{{ aap_user }}"
    aap_password: "{{ aap_pass }}"
    aap_validate_certs: <AAP_STAGING_VALIDATE_CERTS>
...
