---
all:
  children:
    dev:
      hosts:
        localhost:
  vars:
    env: dev
    aap_hostname: "https://aap-aap-operator.apps.127.0.0.1.nip.io"
    aap_username: "{{ aap_user | default('admin') }}"
    aap_password: "{{ aap_pass }}"
    aap_validate_certs: false
...